### ISSUE TITLE
Missing ground connection at C2 & C3

### ISSUE THREAD

**Issue by FrederikWolter** [adlerweb/MoraBoard#3]
Hi,

I do not know if it is because I opened your board in EasyEDA, but I am shown that a ground connection of the two capacitors C2 & C3 is missing, since the ground plane is cut off by the quartz.

![grafik](https://user-images.githubusercontent.com/35914049/76549004-e5febf80-648f-11ea-8d49-4f58a5fe54d3.png)

Isn't that necessary for the way it works?
Or should you make the connection in any case?

Thank you
Frederik

**Comment by adlerweb** [comment]
Yes, GND is required. Seems to be a import bug in EasyEDA – ground is supposed to go between the RTC pins (and other places). 
![gnd](https://user-images.githubusercontent.com/1146482/76550541-9372d280-6492-11ea-8269-dc95cc17d17e.png)
For me it looks like expansion is higher than intended (0.153mm or ~6mil). While you probably could add a trace there I would suggest to check expansion for both sides first, if you can fix it there there's probably a lower chance of errors in other parts of the board too.

**Comment by FrederikWolter** [comment]
> looks like expansion is higher than intended (0.153mm or ~6mil)

It Works.
I almost thought that.
But I did not knew that EasyEDA overwrites these values when importing, nor to which value I should set it.

Thank you very much
Frederik
