### ISSUE TITLE
Why returns isValid false if getMinute() == 0?

### ISSUE THREAD

**Issue by FrederikWolter** [adlerweb/MoraBoard#6]
Hi, 
I am playing around with the uPoff-module.

Now I discovered, what I think is a bug:
` temp = rtc.getMonth();`
` if (temp > 12 || temp == 0){ Serial.print("E:Month "); return false; }`
` temp = rtc.getDay();`
`  if (temp > 31 || temp == 0){ Serial.print("E:Day"); return false; }`
`  temp = rtc.getHour();`
`  if (temp > 24 || temp == 0){ Serial.print("E:Hour"); return false; }`
`  temp = rtc.getMinute();`
`  if (temp > 59 || temp == 0){ Serial.print("E:Minute"); return false;}`
`  temp = rtc.getSecond();`
`  if (temp > 59 || temp == 0) {Serial.print("E:Second"); return false; }`
`  return true;`

Why is it faulty if minute or second == 0?

**Comment by adlerweb** [comment]
Gah - the magic of too much copy&paste and not enough sleep :D. Good catch.
